<?php

/**
 * React to the rejection of a form submission.
 *
 * When honeypot rejects a form submission, it calls this hook with the form ID,
 * the user ID (0 if anonymous) of the user that was disallowed from submitting
 * the form, and the reason (type) for the rejection of the form submission.
 *
 * @param string $form_id
 *   Form ID of the form the user was disallowed from submitting.
 * @param int $uid
 *   0 for anonymous users, otherwise the user ID of the user.
 * @param string $type
 *   String indicating the reason the submission was blocked. Allowed values:
 *     - honeypot: If honeypot field was filled in.
 *     - honeypot_time: If form was completed before the configured time limit.
 */
function honeypot_addl_honeypot_reject($form_id, $uid, $type) {
  drupal_set_message('<pre>'. check_plain(print_r($form_id, TRUE)) .'</pre>');
  if ($form_id == 'mymodule_form') {
    // Log to honeypot tracker
    db_query('INSERT INTO {honeypot_tracker} (form_id, type, uid, hostname, timestamp) VALUES (%s, %s, %d, %s, %d)', $form_id, $type, $user->uid, ip_address(), time());
  }
}

